#!/usr/bin/python3
# Spam filter based on scikit.
# Copyright (c) 2026 Politechnika Wrocławska

from typing import Optional, Any
import bs4
import email
import email.policy
import hashlib
import json
import os
import subprocess
import time
import pickle


def task(task: str, *msg):
    print(f"\033[2m{task:>10}\033[m", *msg)


def setup_dirs():
    dirs_to_create = ['download', 'dataset/spam', 'dataset/notspam', 'cache']
    for dir_path in dirs_to_create:
        if not os.path.isdir(dir_path):
            os.makedirs(dir_path)


def get_cache_state(k: str) -> Optional[Any]:
    """Returns state of K from cache/state.json, or None if missing. """
    if not os.path.exists("cache/state.json"):
        return None
    with open("cache/state.json") as f:
        state = json.load(f)
    return state.get(k, None)


def set_cache_state(k: str, v: Any):
    """Sets cache state of K to V."""
    state = {}
    if os.path.exists("cache/state.json"):
        with open("cache/state.json") as f:
            state = json.load(f)
    state[k] = v
    with open("cache/state.json", "w") as f:
        json.dump(state, f, indent=4)


def save_cache(name: str, data: Any):
    with open(f"cache/{name}.pickle", 'wb') as f:
        pickle.dump(data, f)


def load_cache(name: str) -> Any:
    if not os.path.exists(f"cache/{name}.pickle"):
        return None
    with open(f"cache/{name}.pickle", "rb") as f:
        return pickle.load(f)


def download_training_data():
    """Downloads training data using git clone, then copies the raw email format
    into the dataset / directory. """

    # Use git clone so it doesn't download it every time, but updates automatically.
    task("DOWNLOAD", "stdlib-js/datasets-spam-assassin")
    subprocess.run(['git', 'clone', '--depth=1', 'https://github.com/stdlib-js/datasets-spam-assassin',
                   'download/datasets-spam-assassin'], capture_output=True, text=True)
    head_commit_proc = subprocess.run(['git', '-C', 'download/datasets-spam-assassin',
                                       'rev-parse', 'HEAD'], capture_output=True, text=True)
    head_commit = head_commit_proc.stdout.strip()

    # Caching solution: if we have processed data from the same commit, don't do it again.
    if get_cache_state("dataset-collected-from") == head_commit:
        task("CACHE", "Collected dataset")
        return

    p = 'download/datasets-spam-assassin/data'
    use_dirs = {
        "easy-ham-1": False,
        "easy-ham-2": False,
        "hard-ham-1": False,
        "spam-1": True,
        "spam-2": True
    }

    task("TASK", "Collecting sources")

    for dir_name, is_spam in use_dirs.items():
        for filename in os.listdir(f"{p}/{dir_name}"):
            # In this case, email sources are under the .text key in every JSON file.

            if not filename.endswith('.json'):
                continue

            with open(f"{p}/{dir_name}/{filename}") as f:
                json_blob = json.load(f)
            if "text" not in json_blob:
                continue

            # The hashed email serves as an ID.

            text = json_blob["text"]
            hash = hashlib.sha1(bytes(text, 'utf8')).hexdigest()
            dest = "dataset/spam" if is_spam else "dataset/notspam"

            with open(f"{dest}/{hash}", "w") as f:
                f.write(text)

    set_cache_state("dataset-collected-from", head_commit)


class SpamFilter:
    """Processes all data from the given dataset, fits data to models and predicts. """

    # format is { mail_hash: [is_spam, text] }
    emails: dict[str, list]

    def __init__(self, dataset_path: str):
        self.emails = {}
        dataset_commit = get_cache_state("dataset-collected-from")
        cached_emails = load_cache(f"parsed-{dataset_commit}")
        if cached_emails:
            task("CACHE", "Parsed emails")
            self.emails = cached_emails
        else:
            self.load_emails(dataset_path)
            save_cache(f"parsed-{dataset_commit}", self.emails)

        task("TASK", f"\033[1mLoaded {len(self.emails)} emails\033[m")

    def load_emails(self, dataset_path):
        task("TASK", "Processing all emails...")
        skipped = 0

        for subdir in ["spam", "notspam"]:
            for mail_hash in os.listdir(f"{dataset_path}/{subdir}"):
                p = f"{dataset_path}/{subdir}/{mail_hash}"

                start_time = time.time()
                text = self._text_from_mail(p)
                processing_took = time.time() - start_time

                if text:
                    if processing_took > 0.015:
                        task(
                            "WARN", f"\033[33m{p}\033[m took very long to process:", f"{int(processing_took * 1000)} ms")
                    self.emails[mail_hash] = [
                        True if subdir == "spam" else False,
                        text
                    ]

                if not text:
                    task("ERROR", f"\033[31m{p}\033[m failed")
                    skipped += 1

        task("TASK",
             f"\033[1mDataset has {len(self.emails)} records\033[m,",
             f"skipped {skipped} due to processing errors")

    def _get_content(self, mime_part):
        """Some emails have weird character sets like "DEFAULT", so we just turn
        them into UTF-8 and hope for the best. """

        charset = mime_part.get_content_charset("utf-8")
        weird_charsets = ["default", "default_charset",
                          "chinesebig5", "unknown-8bit", "gb2312_charset"]
        if charset.lower() in weird_charsets:
            mime_part.set_param("charset", "utf-8", header="Content-Type")
        return mime_part.get_content()

    def _text_from_mail(self, mail_path: str) -> Optional[str]:
        """Parse raw email format from the path, returns visible text or None. """

        with open(mail_path) as f:
            m: email.message.EmailMessage = email.message_from_file(
                f, policy=email.policy.default)
        return self._find_body(m)

    def _text_from_html(self, html_text: str) -> Optional[str]:
        """Returns only the visible text from a HTML blob, or None on failure. """
        try:
            body = bs4.BeautifulSoup(html_text, 'html.parser').get_text()
            return body
        except Exception:
            task("ERROR", "Failed to parse HTML")
            return None

    def _find_body(self, m: email.message.EmailMessage) -> Optional[str]:
        """Find text body for any given EmailMessage. Returns the raw text string
        or None on failure. """

        # Different multipart types may have meaning in the real world, but we only
        # care about the text anyway. Note that we also append multipart/report to
        # this list, even if the mails are generated by a machine we find the text
        # blob about "was not delivered". We are filtering against the email the user
        # gets, and not the underlying reported RFC822 payload. See
        # dataset/notspam/3b082669989941c5a0cc121af7ec212b806571b7 as an example.
        accepted_multiparts = ['multipart/alternative', 'multipart/related',
                               'multipart/mixed', 'multipart/signed', 'multipart/report']
        content_type = m.get_content_type()
        body = ''

        if content_type == 'text/plain':
            body = self._get_content(m)
        elif content_type == 'text/html':
            body = self._text_from_html(self._get_content(m))
        elif content_type in accepted_multiparts:
            for part in m.walk():
                part_content_type = part.get_content_type()
                if part_content_type == 'text/plain':
                    body = self._get_content(part)
                    break
                if part_content_type == 'text/html':
                    body = self._text_from_html(self._get_content(part))
                    break
            if not body:
                task("ERROR", "Cannot find working text format in email")
                return None
        else:
            task("ERROR", "Unsupported Content-Type while processing emails:", content_type)
            return None
        return body


def main():
    setup_dirs()
    download_training_data()
    SpamFilter('dataset')


if __name__ == '__main__':
    try:
        main()
    except KeyboardInterrupt:
        print("\nInterrupted by user, exiting.")
